export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#4fc3f7",
        "surface-tint": "#75d1ff",
        "on-primary-fixed-variant": "#004d67",
        "background": "#12121f",
        "surface-container-lowest": "#0d0d1a",
        "on-secondary-container": "#b4b5b5",
        "surface-container": "#1e1e2c",
        "surface-bright": "#383847",
        "primary": "#9adbff",
        "on-background": "#e3e0f4",
        "surface-dim": "#12121f",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#45455b",
        "on-error": "#690005",
        "outline": "#889299",
        "on-surface-variant": "#bdc8d0",
        "surface-container-low": "#1a1a28",
        "surface-container-high": "#292937",
        "on-tertiary-fixed": "#1a1a2e",
        "on-primary": "#003548",
        "primary-fixed": "#c2e8ff",
        "on-tertiary": "#2f2e43",
        "secondary-container": "#454747",
        "primary-fixed-dim": "#75d1ff",
        "tertiary-fixed-dim": "#c6c4df",
        "on-secondary-fixed": "#1a1c1c",
        "inverse-on-surface": "#2f2f3d",
        "tertiary": "#d3d0ec",
        "secondary-fixed": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e3e0f4",
        "inverse-primary": "#006688",
        "on-secondary": "#2f3131",
        "on-surface": "#e3e0f4",
        "secondary": "#c6c6c7",
        "tertiary-fixed": "#e2e0fc",
        "surface-container-highest": "#343342",
        "on-tertiary-container": "#47465d",
        "on-secondary-fixed-variant": "#454747",
        "error-container": "#93000a",
        "tertiary-container": "#b7b5d0",
        "on-primary-fixed": "#001e2b",
        "outline-variant": "#3e484f",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-variant": "#343342",
        "surface": "#12121f",
        "on-primary-container": "#004e69",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "gutter": "16px",
        "unit": "4px",
        "slash-angle": "15deg",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Syne"],
        "label-caps": ["Space Mono"],
        "headline-xl": ["Syne"],
        "headline-lg": ["Syne"],
        "body-md": ["Inter"],
        "label-sm": ["Space Mono"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.2em", fontWeight: "700" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "400" }],
      },
    },
  },
};
